### ISSUE TITLE
evaluation.py does not give the same results as README.md

### ISSUE THREAD

**Issue by maidh126** [john-cardiff/-cyborg-cage-2#1]
hi, I run evaluation.py file but its giving me different reward scores. what should i do to have the same scores from README?

using CybORG v2.1, Scenario2

MAX_EPS = 1000
agent_name = 'Blue'
random.seed(0)
ChallengeWrapper2

Average reward for red agent B_lineAgent and steps 30 is: -5.3542 with a standard deviation of 3.9774089734577367
Average reward for red agent RedMeanderAgent and steps 30 is: -5.537 with a standard deviation of 1.2877069500430556

Average reward for red agent B_lineAgent and steps 50 is: -12.956400000000002 with a standard deviation of 8.108878649539221
Average reward for red agent RedMeanderAgent and steps 50 is: -8.823699999999999 with a standard deviation of 2.2577612353381817

Average reward for red agent B_lineAgent and steps 100 is: -36.891100000000044 with a standard deviation of 15.004240668158754
Average reward for red agent RedMeanderAgent and steps 100 is: -16.4722 with a standard deviation of 3.8317527959785607

![image](https://github.com/john-cardiff/-cyborg-cage-2/assets/85572480/29b0d563-2966-45ef-ad4b-cd01ad9f3657)

**Comment by john-cardiff** [comment]
It's probably because the CyBORG environment has changed since submission. See https://github.com/cage-challenge/cage-challenge-2/commit/3ead7fde17b5b33a42e6cb1758992b2c1c724b4a and https://github.com/cage-challenge/cage-challenge-2/commit/9421c8e985627810c5cac2abf0bcb62dfa6749fc.

If you are testing it in the same environment as the challenge (before the two fixes, so where the policy was trained), then there is an issue and I'll take a look! However, I would recommend retraining with the fixes!

**Comment by maidh126** [comment]
thank you very much! 

the results from your Readme and from leader board are not the same. is that only because of random seed or also because you are using the ChallengeWrapper2? to have the same result as leader board, what random seed and wrapper you suggest?

**Comment by john-cardiff** [comment]
The CC2 team used random.seed(153) for evaluation. If you run the code in the CyBORG version prior to the two fixes, then it should be the same results as the leaderboard. But again, I would recommend retraining with the latest version (with the fixes), as the policy will be far more interesting and the trajectories will make sense. Good luck!
